-- CreateTable
CREATE TABLE "Client" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'cliente',
    "email" TEXT,
    "phone" TEXT,
    "cpf" TEXT,
    "birthDate" TEXT,
    "motherName" TEXT,
    "rg" TEXT,
    "rgIssueDate" TEXT,
    "rgIssueState" TEXT,
    "zip" TEXT,
    "street" TEXT,
    "number" TEXT,
    "complement" TEXT,
    "district" TEXT,
    "city" TEXT,
    "state" TEXT,
    "bank" TEXT,
    "accountType" TEXT DEFAULT 'corrente',
    "agency" TEXT,
    "account" TEXT,
    "totalValue" REAL NOT NULL DEFAULT 0,
    "percentage" REAL NOT NULL DEFAULT 0,
    "referrerId" TEXT,
    "docFront" TEXT,
    "docBack" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
